image_angle = testing.YA;
team = -1;
alarm_set(0, 20);
audio_play_sound(tu_2_sound,9,false);
audio_play_sound(tu_2_sound,9,false);
audio_play_sound(tu_2_sound,9,false);
cid = 1;
cid_id  = asset_get_index("testing" + string(cid));
image_alpha = 0.6;
dmg = 25;