arm_all_normal();
a_cooltime = 1000;
buff_index = spr_wing1;
buff_time = 5;
server77_equal(serve_val.buff_index, buff_index, buffer_u16);
right_arm_yscale = -1;
left_arm_yscale = -1;
server78_create_instace(ik_skill4, x, y);
arm_type = "attack";
arm_type_more = "a_w";