a_possible = 1;
extra_speed = 0;
arm_type = "normal";
arm_type_more = "none"
view_where = 0;
effect_index = spr_none;
view_visible[1] = false;
view_visible[0] = true;
obj_telescope_view.tele = false;
cancle_able = false;
server77_equal(serve_val.cancle_able, cancle_able, buffer_bool);