arm_type = "normal";
a_possible = true;
right_arm_YA = YA
left_arm_YA = YA
left_foot_YA = YA
right_foot_YA = YA
charge = false;
right_foot_deltay = 0;
left_foot_deltay = 0;
go_to_speed = 0;
server77_equal(serve_val.cancle_able, 0, buffer_bool);