server78_create_instace(pota_skill11, x, y);
only_hat = true;
server77_equal(serve_val.only_hat, only_hat, buffer_bool);
a_possible = false;
effect_index = spr_none;
arm_type = "attack"
arm_type_more = "arm_lock4"
go_to_speed = 10;
a_cooltime = -1;
cancle_able = true;
server77_equal(serve_val.cancle_able, cancle_able, buffer_bool)