a_cooltime = 20;
arm_type = "attack"
spr_armr_more = spr_bada2;
left_goto_YA = image_angle;
right_arm_YA = image_angle + 10;
right_goto_YA = image_angle - 10;
arm_spin_able = 1;
arm_spin_speed = 20;
spin_able = true;